name: gg570_d200
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.0
  - matplotlib==3.10.7
  - scikit-learn==1.5.2
  - xgboost==3.2.0
  - pandas==3.0.1
  - ipykernel==7.2.0
  - tensorflow==2.20.0
  - econml==0.15.1
